import { Metadata, NextPage } from "next";
import { HomeContainer, Header } from "@/src/components";

export const metadata: Metadata = {
  title: 'Início',
  description: 'Generated by create next app',
}

const Home: NextPage = () => {
  return (
    <>
      <Header />
      <main >
        <HomeContainer />
      </main>
    </>
  )
}

export default Home